import type {Metadata} from "next";
import 'modern-normalize';
import {Manrope, Inter} from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import Header from "@/components/Header/Header";
import TanStackProvider from "@/TanStackProvider/TanStackProvider";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import {Toaster} from "react-hot-toast";

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
    weight: ["400", "700"],
    display: "swap",
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    display: "swap",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    return (
        <html
            lang="en"
            className={`${manrope.variable} ${inter.variable}`}
            data-scroll-behavior="smooth"
        >
        <body>
        <TanStackProvider>
            <Header />
            <main>{children}</main>
            <Toaster/>
            <ReactQueryDevtools initialIsOpen={false} />
        </TanStackProvider>
        </body>
        </html>
    );
}
